name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        timeout-minutes: 2

      - name: Run linting
        run: npm run lint
        timeout-minutes: 2

      - name: Run type checking
        run: npm run check
        timeout-minutes: 2

      - name: Build project
        run: npm run build
        timeout-minutes: 3

      - name: Run server-side tests
        run: npx vitest run --project server
        timeout-minutes: 2

      - name: Install Playwright browsers (for full test suite)
        run: npx playwright install --with-deps chromium
        continue-on-error: true
        timeout-minutes: 10

      - name: Run full test suite
        run: npm run test
        timeout-minutes: 3

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-output-node-${{ matrix.node-version }}
          path: .svelte-kit/output/
          retention-days: 7
